version: '3.3'
services:
  database:
    image: mongo:4.2.5
    ports:
      - '27017:27017' 
  app:
    build: .
    environment:
      WAIT_HOSTS: database:27017
      CLIENT_ID: "changeMe" 
      CLIENT_SECRET: "changeMe"
      REDIRECT_URI: "http://localhost:8080/spotify" 
    ports:       
      - '8080:8080'