version: '3.3'
services:
  database:
    image: mongo:7.0
    ports:
      - '27017:27017' 
  app:
    build: .
    environment:
      WAIT_HOSTS: database:27017 
    ports:       
      - '8080:8080'